# Generated by Django 4.0.3 on 2022-03-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.IntegerField(default=0.0),
        ),
    ]
