# Generated by Django 4.0.3 on 2022-03-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produit',
        ),
    ]
